 
spring.application.name=smartcampus
server.port=${PORT:8091}
 
spring.data.mongodb.uri=${MONGODB_URI}

# =========================
# GITHUB OAUTH2
# =========================
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email,read:user

# =========================
# GOOGLE OAUTH2
# =========================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# =========================
# JWT
# =========================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

 
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
 
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

app.upload.dir=${UPLOAD_DIR:uploads}

 
app.base-url=${BACKEND_URL:http://localhost:8091}

 
logging.level.com.sliit=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
 
app.admin.emails=${ADMIN_EMAILS:}
 
spring.devtools.restart.enabled=false